### ISSUE TITLE
Test and update bundled widgets

### ISSUE THREAD

**Issue by jesseleite** [statamic/cms#219]
- [x] Getting started widget (See #43)
- [x] Collection widget (See #224)
- [x] Template widget
- [x] Updater widget (See #229)
