### ISSUE TITLE
Create a "conditions builder" field to be used when configuring a field

### ISSUE THREAD

**Issue by jesseleite** [statamic/cms#259]
### Concept...

[ pick a field ] [ pick an operator ] [ type a value ]
[ add another field ]

### Todo...

- [x] Convert from blueprint format to editable object (ie. separate operator from value)
- [x] Implement conditions builder form
- [x] Convert from form back to blueprint format
- [x] Save to blueprint
